// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(AsignaturaContext))]
    partial class AsignaturaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Entity.Docente", b =>
                {
                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Correo")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Pais")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SobreDocente")
                        .HasColumnType("varchar(300)");

                    b.HasKey("Identificacion");

                    b.ToTable("Docentes");
                });
#pragma warning restore 612, 618
        }
    }
}
